### ISSUE TITLE
This repo is empty

### ISSUE THREAD

**Issue by jeffmaher** [nigelpoulton/TheK8sBook#1]
Reading through ["The Kuberenetes Book"](https://www.amazon.com/Kubernetes-Book-Version-November-2018-ebook-dp-B072TS9ZQZ/dp/B072TS9ZQZ/ref=mt_kindle?_encoding=UTF8&me=&qid=1516718119) right now and was hoping to find the YAML examples in this repo, but it's empty.

![image](https://user-images.githubusercontent.com/950486/50449636-8b169200-08f6-11e9-9ae6-e7eb98184f3a.png)

**Comment by jaydo1** [comment]
am also trying to follow along with the book but can't find the yaml files required

**Comment by chrisjeffreyuk** [comment]
As mentioned the Repo is empty.

**Comment by eanhuddleston** [comment]
@nigelpoulton 	where can these files be found?

**Comment by chipzoller** [comment]
Calling @nigelpoulton another user looking for this repo.

**Comment by nigelpoulton** [comment]
Oops. My bad. All sorted.  I've uploaded the files and am busy preparing an update to the book, so will go through all examples etc and make sure they work.
