### ISSUE TITLE
kubectl get rs vs kubectl describe rs .. maybe a typo?

### ISSUE THREAD

**Issue by sushruthajirnis** [nigelpoulton/TheK8sBook#11]
On page  85 of the paperback edition the text describes the `kubectl describe rs` command  but the example has the `kubectl get rs` command. The output of however is from the describe command.

**Comment by nigelpoulton** [comment]
Cheers @sushruthajirnis I've noted this in the manuscript so that it'll be fixed in the next release. Many thanks!
