### ISSUE TITLE
Chapter 5 app connection refused

### ISSUE THREAD

**Issue by Muswell** [nigelpoulton/TheK8sBook#13]
In the chapter on namespaces I'm running into problems getting the-bus app to accept a curl request. Everything seems to match the output from the examples in the book with the exception of the ServiceAccounts last-applied-configuration warning when applying shield-app.yml. If I go into the pod and install curl I get a response when hitting localhost.  Any idea what I'm doing wrong or how I can troubleshoot?

**kubectl version**
Client: v1.21
Server: v1.21

**k3d version**
k3d version v4.4.7
k3s version v1.21.2-k3s1 (default)

```
kubectl apply -f shield-app.yml
Warning: resource serviceaccounts/default is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
serviceaccount/default configured
service/the-bus created
pod/triskelion created
```

```
kubectl get pods -n shield
NAME         READY   STATUS    RESTARTS   AGE
triskelion   1/1     Running   0          117s
```

```
kubectl get svc -n shield
NAME      TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
the-bus   NodePort   10.43.196.219   <none>        8080:31112/TCP   2m51s
```

```
kubectl describe svc -n shield
Name:                     the-bus
Namespace:                shield
Labels:                   <none>
Annotations:              <none>
Selector:                 env=marvel
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.196.219
IPs:                      10.43.196.219
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  31112/TCP
Endpoints:                10.42.1.3:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```

```
curl localhost:31112
curl: (7) Failed to connect to localhost port 31112: Connection refused
```

```
kubectl exec -it triskelion -n shield -- sh
/usr/src/app # curl localhost:8080
<!DOCTYPE html>
<html>
<head>
    <title>AOS</title>
    <link rel="stylesheet" type="text/css" href="/css/main.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu:300" >
</head>
<body>

  <div class="main">
    <img src="/images/image.png"/>
    <div class="content">
      <div id="message">
  Agents of S.H.I.E.L.D
</div>
<div id="info">
  <table>
    <tr>
      <th>Pod/container/host that serviced this request:</th>
      <td>triskelion</td>
    </tr>
  </table>

</div>
    </div>
  </div>

</body>
</html>
```

**Comment by nigelpoulton** [comment]
Really sorry I missed this one @Muswell 

I'm closing due to age and the fact we're on K8s 1.26 now.

Again, really sorry I missed it.

**Comment by hughpv** [comment]
Having the same problem. I can't figure out how `localhost:31112` (on my laptop) is supposed to get routed to the Pod that exposes port 8080.

I'm using k3d, if that makes any difference... when I run `docker ps -a` it doesn't show that port 31112 is being mapped anywhere.

**Comment by hughpv** [comment]
Update: tried running it with k3d on Ubuntu Server 22.04 (my previous attempt was on a Mac) and it looks a little better, but something is still wrong.

The text says I should be able to run `curl localhost:31112` from the host and get a response. I don't see that working on the Mac and I also don't see it working on Ubuntu.

So I looked up the IP address of the node where the Pod is running:
```
kubectl get nodes -o wide
NAME               STATUS   ROLES                  AGE     VERSION        INTERNAL-IP   EXTERNAL-IP   OS-IMAGE   KERNEL-VERSION      CONTAINER-RUNTIME
k3d-tkb-server-0   Ready    control-plane,master   2m38s   v1.26.1+k3s1   172.18.0.2    <none>        K3s dev    5.15.0-60-generic   containerd://1.6.15-k3s1
k3d-tkb-agent-0    Ready    <none>                 2m34s   v1.26.1+k3s1   172.18.0.3    <none>        K3s dev    5.15.0-60-generic   containerd://1.6.15-k3s1
k3d-tkb-agent-2    Ready    <none>                 2m33s   v1.26.1+k3s1   172.18.0.5    <none>        K3s dev    5.15.0-60-generic   containerd://1.6.15-k3s1
k3d-tkb-agent-1    Ready    <none>                 2m33s   v1.26.1+k3s1   172.18.0.4    <none>        K3s dev    5.15.0-60-generic   containerd://1.6.15-k3s1
```

It turns out it's running on `k3d-tkb-server-0`. So when I run `curl 172.18.0.2:31112`, I get the expected output. (I still don't get that on Mac, but Mac networking is... different.)

**Comment by hughpv** [comment]
Still not ideal, but here's a way that even works on Mac:

You need two terminals.

1. In the first terminal, run `kubectl port-forward -n shield service/the-bus 31112:8080` ... this just sits there and blocks.
2. In the second terminal, run `curl localhost:31112`. You'll get the expected output.

When done, you'll have to stop the command in the first terminal with ^C.
