### ISSUE TITLE
More docker images with different architectures

### ISSUE THREAD

**Issue by tobiolalusi** [nigelpoulton/TheK8sBook#15]
I was trying to follow the tutorial from the K8s book, but I unfortunately couldn't run the manifest files, because the images pulled from docker hub only supports `amd` architectures. I'm following up from my raspberry pi, which has an `arm` architecture. Every time a pod for example tries to run, I keep getting a `CrashLoopBackOff`.

**Comment by nigelpoulton** [comment]
Hi @tobiolalusi I'll look into ARM images. Thanks for highlighting this!

**Comment by jeremy-donson** [comment]
Any updates on ARM images?

**Comment by nigelpoulton** [comment]
Should all be there now @jeremy-donson 

Looks like I'd sorted it out for most of the images a few months back but I couldn't find the source code for a couple. I managed to sort them out today and on Docker Hub all are showing images for `linux/amd64` and `linux/arm64`.

https://hub.docker.com/r/nigelpoulton/k8sbook/tags

**Comment by robertpeteuil** [comment]
The edge tag (`nigelpoulton/k8sbook:edge`) is still missing an Arm64 build & causes the deployment update in Chapter 5 to fail with a CrashLoopBackOff error.

**Comment by nigelpoulton** [comment]
Hi @robertpeteuil so I deprecated the `edge` tag in favour of the `2.0` tag.

It's not ideal as some people are on older versions of the book that still reference `edge`.

Can you let me know the edition of the book you have (if it's paperback the year of publication is listed on the front cover).  Also list the chapter number and name, as they occasionally change.  E.g. at the moment chapter 5 is "Virtual Clusters with Namespaces" but it used to be "Kubernetes Deployments".`

I know I know... it's a pain. Tell me about it ;-)

Oh I uploaded `arm64` and `arm/v7` images just in case.

**Comment by robertpeteuil** [comment]
Thank you.

I'm reading the Kindle edition and it looks like it's the 2019 edition.  I'll contact their support to get the 2022 edition.
