### ISSUE TITLE
Service with NodePort not accessible

### ISSUE THREAD

**Issue by cmantsch** [nigelpoulton/TheK8sBook#21]
I am currently in chapter 4 and the sidecar example for local use does not let me access it with localhost:30001.

I figured out that I need to run `minikube service svc-sidecar`, which solves this problem. Maybe it would be worth mentioning this in the next version of the book.

**Comment by 01binary** [comment]
Just got this issue today - @cmantsch thanks for reporting. I would probably never know until the end of study

**Comment by witwit** [comment]
so one needs to install minicube on top of the whole thing? And then run the service?

**Comment by nigelpoulton** [comment]
I've added some comments to the top of the `sidecar-local.yml` file with the advice from here.
I think last time I checked there were also issues depending on network drivers and even the DNS config of the busybox container in one of the Pods. I'll look to add clarifications to the next edition of the book and to the YAML files in the short term.
Thanks for the input everyone!

**Comment by witwit** [comment]
I have also read somewhere that if you are on Windows and using Docker Desktop configured to run on WSL, then you cannot use "localhost", but should use the hostname of the wsl machine. This did not seem to work in my case, though. I have tried to call "127.0.1.1:30001" without success. The only thing that worked was to run the port-forwarding...
