### ISSUE TITLE
Exercises at "Hands-on with Pods" get error

### ISSUE THREAD

**Issue by pa-uriza** [nigelpoulton/TheK8sBook#25]
When I was following the section "kubectl exec: running commands in Pods" I tried to run the command `kubectl exec hello-pod -- ps aux` after having applied the manifest but I got the error

``` sh
OCI runtime exec failed: exec failed: unable to start container process: exec: "ps": executable file not found in $PATH: unknown
command terminated with exit code 126
```

This is because the current image (`nigelpoulton/k8sbook:1.0`) does not have the `ps` command installed.

Then I tried to install `curl` using `apk add curl` as instructed some lines below but I get the error

``` sh
sh: 1: apk: not found
```

After digging a little, I found that the `apk` command is for Alpine, however, the image is based on Debian. I guess somewhere in time you updated the image to have a different base image but that is causing an error (maybe that caused the above error as well ?).

Finally, I installed both commands using  `apt-get` just to be able to complete the exercise. However, at this moment the instructions for the 2022 version of the book are not compatible with the image available for these exercises.

**Comment by lordz-md** [comment]
Same issue here.

**Comment by nigelpoulton** [comment]
I've fixed this issue in the latest version of the image on Docker Hub.

Basically I had decided to create a smaller image, but the smaller image didn't have the right tools installed.

Should be working now. LMK if it isn't.
