### ISSUE TITLE
Just FYI: deploy.yml is using k8sbook:edge while book shows it should use :latest

### ISSUE THREAD

**Issue by l0thar** [nigelpoulton/TheK8sBook#3]
Just a heads up:

deployments/deploy.yml line 23:
        `image: nigelpoulton/k8sbook:edge`

Book shows the line repeatedly as:
        `image: nigelpoulton/k8sbook:latest`

I wound up doing the rolling update example backwards because I didn't realize it was using edge instead of latest. Not a big deal, but I thought you should be aware.

**Comment by psygo** [comment]
It would be nice to have note somewhe indeed. The same thing happened to me.

**Comment by nigelpoulton** [comment]
Thanks @l0thar @psygo  for the heads-up. I've sorted this.
