### ISSUE TITLE
kubectl exec: running commands in Pods

### ISSUE THREAD

**Issue by logisin** [nigelpoulton/TheK8sBook#30]
### Discussed in https://github.com/nigelpoulton/TheK8sBook/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **logisin** January  1, 2023</sup>
The command `kubectl exec hello-pod -- ps aux` from chapter 4 section "Hands on with pods" gives the following message:
<pre>error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec &quot;fc7ef1a745ffd71b0d28376f80ab706bf896fb8e13c501e66a2889286eda97f9&quot;: OCI runtime exec failed: exec failed: unable to start container process: exec: &quot;ps&quot;: executable file not found in $PATH: unknown
</pre>

In addition after executing the command `kubectl exec -it hello-pod -- sh` I get into the shell but the command  `apk add curl `
 responds with
<pre>sh: 1: apk: not found
</pre>
</div>

**Comment by nigelpoulton** [comment]
This was my bad. I cahnged the base image to be a smaller one and... well... the smaller one didn't have the required utilities. Should be fixed if you clone the latest version of the repo.

Thanks for the heads-up.
