### ISSUE TITLE
psa folder is missing

### ISSUE THREAD

**Issue by AntonioND** [nigelpoulton/TheK8sBook#32]
In chapter 15: "Threat modeling Kubernetes", section "PSA examples" mentions folder psa, but it isn't present in the repository.

> The book’s GitHub repo can be found here.
>
> `https://github.com/nigelpoulton/TheK8sBook`
>
> Be sure to run the following commands from the **psa** directory.

**Comment by StanleyPan** [comment]
Having the same issue.

**Comment by raheelkhan** [comment]
Is there any update on it ?

**Comment by nigelpoulton** [comment]
Added missing folder. My bad. Thanks for your patience.
