### ISSUE TITLE
service-discovery folder missing?

### ISSUE THREAD

**Issue by jerrycan321** [nigelpoulton/TheK8sBook#5]
Hi folks.
In the Kindle edition of The Kubernetes Book (Feb 2020) location 1648 it mentions a folder called service-discovery containing files such as sd-example.yml in this github repo - 
I have what I believe is the latest commit of the repo  (f1aabcbf3ab1fd15f63971823b2d9fc6e04dc820) but I don't see the folder or its contents. I must be missing something... any ideas?
Regards
Jerome

**Comment by nigelpoulton** [comment]
Thanks @jerrycan321 I've fixed this. Many thanks for the heads-up.
