### ISSUE TITLE
Can a service be accessed by its port only?

### ISSUE THREAD

**Issue by AnatoliiStepaniuk** [nigelpoulton/TheK8sBook#6]
<img width="584" alt="Screenshot 2020-08-22 at 13 22 37" src="https://user-images.githubusercontent.com/11556624/90954160-adb9cf00-e47a-11ea-87c5-841bf2dd6145.png">

Does it mean that the Service can be accessed by its internal port only? (without specifying the IP).

**Comment by nigelpoulton** [comment]
Good spot @AnatoliiStepaniuk 

You can only connect via ClusterIP + port or Name + port. I'll clarify this in the next edition!
